/**
 * Bundled Demo Repository
 *
 * A realistic payment gateway microservice with intentional issues
 * for MSE to discover through real analysis. Every file here will be
 * analyzed by the engine — nothing is pre-computed or pre-classified.
 *
 * Known planted issues (the engine must discover these independently):
 * - Webhook route missing HMAC signature verification
 * - Users POST route missing auth middleware
 * - Port mismatch between README (3000) and code (8080)
 * - Transaction boundary without guaranteed rollback
 * - OpenAPI spec requires auth header but code doesn't check it
 */

/** @returns {import('../types').RepositorySnapshot} */
export function loadDemoRepository() {
  const files = [
    {
      path: 'server.js',
      content: [
        "import express from 'express';",
        "import { webhookRouter } from './src/routes/webhook.js';",
        "import { usersRouter } from './src/routes/users.js';",
        "import { ordersRouter } from './src/routes/orders.js';",
        "",
        "const app = express();",
        "app.use(express.json());",
        "",
        "app.use('/webhook', webhookRouter);",
        "app.use('/users', usersRouter);",
        "app.use('/orders', ordersRouter);",
        "",
        "const PORT = process.env.PORT || 8080;",
        "app.listen(PORT, () => {",
        "  console.log(`Server running on port ${String.raw`${PORT}`}`);",
        "});",
      ].join('\n'),
    },
    {
      path: 'src/routes/webhook.js',
      content: [
        "import express from 'express';",
        "import { pool } from '../db/pool.js';",
        "",
        "export const webhookRouter = express.Router();",
        "",
        "webhookRouter.post('/github', async (req, res) => {",
        "  const event = req.headers['x-github-event'] || 'unknown';",
        "  const payload = req.body;",
        "",
        "  try {",
        "    await processGitHubEvent(event, payload);",
        "    res.json({ received: true, event });",
        "  } catch (err) {",
        "    res.status(500).json({ error: err.message });",
        "  }",
        "});",
        "",
        "async function processGitHubEvent(event, payload) {",
        "  await new Promise(r => setTimeout(r, 10));",
        "  console.log(`[Webhook] Processing event: ${String.raw`${event}`}`);",
        "  await pool.query(",
        "    'INSERT INTO audit_events (type, data) VALUES ($1, $2)',",
        "    [event, JSON.stringify(payload)]",
        "  );",
        "}",
      ].join('\n'),
    },
    {
      path: 'src/routes/users.js',
      content: [
        "import express from 'express';",
        "import { listUsers, createUser, getUser } from '../controllers/usersController.js';",
        "",
        "export const usersRouter = express.Router();",
        "",
        "usersRouter.get('/', listUsers);",
        "usersRouter.get('/:id', getUser);",
        "",
        "usersRouter.post('/', async (req, res) => {",
        "  const user = await createUser(req.body);",
        "  res.status(201).json(user);",
        "});",
      ].join('\n'),
    },
    {
      path: 'src/routes/orders.js',
      content: [
        "import express from 'express';",
        "import { requireAuth } from '../controllers/usersController.js';",
        "import { listOrders, createOrder } from '../controllers/ordersController.js';",
        "",
        "export const ordersRouter = express.Router();",
        "",
        "ordersRouter.get('/', requireAuth, listOrders);",
        "ordersRouter.post('/', requireAuth, createOrder);",
      ].join('\n'),
    },
    {
      path: 'src/controllers/webhookController.js',
      content: [
        "import crypto from 'crypto';",
        "",
        "export function verifyWebhookSignature(payload, signature, secret) {",
        "  if (!signature || !secret) return false;",
        "  const hmac = crypto.createHmac('sha256', secret);",
        "  const digest = 'sha256=' + hmac.update(payload).digest('hex');",
        "  return crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(digest));",
        "}",
      ].join('\n'),
    },
    {
      path: 'src/controllers/usersController.js',
      content: [
        "import jwt from 'jsonwebtoken';",
        "",
        "export function requireAuth(req, res, next) {",
        "  const header = req.headers['authorization'];",
        "  if (!header || !header.startsWith('Bearer ')) {",
        "    return res.status(401).json({ error: 'Missing or invalid bearer token' });",
        "  }",
        "  const token = header.split(' ')[1];",
        "  try {",
        "    req.user = jwt.verify(token, process.env.JWT_SECRET || 'dev-secret');",
        "    next();",
        "  } catch (err) {",
        "    return res.status(403).json({ error: 'Invalid authentication token' });",
        "  }",
        "}",
        "",
        "export async function listUsers(req, res) {",
        "  res.json({ users: [] });",
        "}",
        "",
        "export async function getUser(req, res) {",
        "  res.json({ user: { id: req.params.id } });",
        "}",
        "",
        "export async function createUser(data) {",
        "  return { id: 'usr_' + Date.now(), ...data };",
        "}",
      ].join('\n'),
    },
    {
      path: 'src/controllers/ordersController.js',
      content: [
        "import { pool } from '../db/pool.js';",
        "",
        "export async function listOrders(req, res) {",
        "  const result = await pool.query(",
        "    'SELECT * FROM orders WHERE user_id = $1',",
        "    [req.user.id]",
        "  );",
        "  res.json({ orders: result.rows });",
        "}",
        "",
        "export async function createOrder(req, res) {",
        "  const { amount, currency, items } = req.body;",
        "  const result = await pool.query(",
        "    'INSERT INTO orders (user_id, amount, currency, status) VALUES ($1, $2, $3, $4) RETURNING *',",
        "    [req.user.id, amount, currency, 'PENDING']",
        "  );",
        "  res.status(201).json({ order: result.rows[0] });",
        "}",
      ].join('\n'),
    },
    {
      path: 'src/db/pool.js',
      content: [
        "const state = {",
        "  activeClients: 0,",
        "  inTransaction: false,",
        "};",
        "",
        "export const pool = {",
        "  async query(text, params) {",
        "    return { rows: [], rowCount: 0 };",
        "  },",
        "",
        "  async beginTransaction() {",
        "    state.inTransaction = true;",
        "    return this.query('BEGIN');",
        "  },",
        "",
        "  async commit() {",
        "    state.inTransaction = false;",
        "    return this.query('COMMIT');",
        "  }",
        "};",
      ].join('\n'),
    },
    {
      path: 'specs/README.md',
      content: [
        "# Payment Gateway Microservice",
        "",
        "## Configuration",
        "",
        "- Service Port: 3000",
        "- Auth Scheme: HMAC-SHA256 required for all webhook endpoints",
        "- Database: PostgreSQL on port 5432 with auto-rollback transactions",
        "",
        "## API Endpoints",
        "",
        "- POST /webhook/github — receives GitHub webhook events",
        "- GET /users — list all users",
        "- POST /users — create a new user (requires authentication)",
        "- GET /orders — list orders for authenticated user",
        "- POST /orders — create an order (requires authentication)",
        "",
        "## Environment Variables",
        "",
        "- PORT — server listening port (default: 3000)",
        "- DATABASE_URL — PostgreSQL connection string",
        "- JWT_SECRET — secret for signing JWT tokens",
        "- WEBHOOK_SECRET — secret for verifying GitHub webhook HMAC signatures",
        "- NODE_ENV — environment (development/production)",
      ].join('\n'),
    },
    {
      path: 'specs/openapi.yaml',
      content: [
        "openapi: 3.0.3",
        "info:",
        "  title: Payment Gateway API",
        "  version: 1.0.0",
        "  description: Payment gateway microservice API",
        "servers:",
        "  - url: http://localhost:8080",
        "    description: Development server",
        "paths:",
        "  /webhook/github:",
        "    post:",
        "      summary: GitHub Webhook Receptor",
        "      parameters:",
        "        - name: X-Hub-Signature-256",
        "          in: header",
        "          required: true",
        "          schema:",
        "            type: string",
        "      responses:",
        "        '200':",
        "          description: Event successfully processed",
        "        '401':",
        "          description: Missing or invalid HMAC signature",
        "  /users:",
        "    get:",
        "      summary: List all users",
        "      responses:",
        "        '200':",
        "          description: User list",
        "    post:",
        "      summary: Create a new user",
        "      security:",
        "        - bearerAuth: []",
        "      responses:",
        "        '201':",
        "          description: User created",
        "  /orders:",
        "    get:",
        "      summary: List orders",
        "      security:",
        "        - bearerAuth: []",
        "      responses:",
        "        '200':",
        "          description: Order list",
        "    post:",
        "      summary: Create an order",
        "      security:",
        "        - bearerAuth: []",
        "      responses:",
        "        '201':",
        "          description: Order created",
      ].join('\n'),
    },
    {
      path: '.env.example',
      content: [
        "PORT=3000",
        "DATABASE_URL=postgresql://localhost:5432/payment_gateway",
        "JWT_SECRET=change-me-in-production",
        "WEBHOOK_SECRET=change-me-in-production",
        "NODE_ENV=development",
      ].join('\n'),
    },
    {
      path: 'package.json',
      content: JSON.stringify({
        name: 'payment-gateway',
        version: '1.0.0',
        type: 'module',
        main: 'server.js',
        scripts: {
          start: 'node server.js',
          dev: 'node --watch server.js',
        },
        dependencies: {
          express: '^4.18.2',
          jsonwebtoken: '^9.0.0',
          pg: '^8.11.0',
          crypto: '^1.0.1',
        },
      }, null, 2),
    },
  ];

  return {
    files: files.map(f => ({
      path: f.path,
      content: f.content,
      language: detectLanguage(f.path),
    })),
    metadata: {
      source: 'demo',
      name: 'payment-gateway',
      loadedAt: new Date().toISOString(),
      description: 'Demo payment gateway microservice with intentional issues',
    },
  };
}

/** @param {string} filePath */
function detectLanguage(filePath) {
  const ext = filePath.split('.').pop()?.toLowerCase();
  const map = {
    js: 'javascript', mjs: 'javascript', cjs: 'javascript',
    ts: 'typescript', tsx: 'typescript', jsx: 'javascript',
    json: 'json', yaml: 'yaml', yml: 'yaml',
    md: 'markdown', py: 'python', rb: 'ruby',
    go: 'go', rs: 'rust', java: 'java', cs: 'csharp',
    html: 'html', css: 'css', sql: 'sql',
    proto: 'protobuf', toml: 'toml', xml: 'xml',
  };
  return map[ext] || 'plaintext';
}
