/**
 * Canonical Enterprise Demonstration Fixture Loader
 *
 * Provides the in-memory representation of fixtures/enterprise-payment-core
 * for reproducible MSE analysis and workbench demonstrations.
 */

/** @returns {import('../types').RepositorySnapshot} */
export function loadEnterpriseFixture() {
  const files = [
    {
      path: 'package.json',
      content: JSON.stringify({
        name: 'enterprise-payment-core',
        version: '2.4.0',
        private: true,
        description: 'Enterprise Core Payment and Double-Entry Settlement Gateway',
        type: 'module',
        main: 'src/server.ts',
        scripts: {
          start: 'ts-node src/server.ts',
          test: 'vitest run',
        },
        dependencies: {
          crypto: '^1.0.1',
          dotenv: '^16.4.5',
          express: '^4.19.2',
          jsonwebtoken: '^9.0.2',
          pg: '^8.12.0',
        },
        devDependencies: {
          '@types/express': '^4.17.21',
          '@types/jsonwebtoken': '^9.0.6',
          '@types/node': '^20.14.9',
          '@types/pg': '^8.11.6',
          typescript: '^5.5.2',
          vitest: '^2.0.0',
        },
      }, null, 2),
    },
    {
      path: '.env.example',
      content: [
        'PORT=3000',
        'DATABASE_URL=postgresql://postgres:postgres@localhost:5432/payment_core',
        'JWT_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0v9jS2l5j...\\n-----END PUBLIC KEY-----',
        'STRIPE_WEBHOOK_SECRET=whsec_test_secret_key_12345',
        'NODE_ENV=development',
      ].join('\n'),
    },
    {
      path: 'README.md',
      content: [
        '# Enterprise Payment Core Microservice',
        '',
        'Mission-critical payment settlement and double-entry ledger backend service.',
        '',
        '## Architecture & Configuration',
        '',
        '- Service Port: 3000',
        '- Auth Scheme: HMAC authentication required for all payment services and API callers',
        '- Webhook Security: HMAC-SHA256 signature verification required for all webhook endpoints',
        '- Database: PostgreSQL on port 5432 with atomic double-entry balance constraints',
        '',
        '## Service Boundaries',
        '',
        'The microservice consists of four core modular boundaries:',
        '1. `src/server.ts` — Ingress orchestration, express route mounting, and HTTP lifecycle',
        '2. `src/config.ts` — Centralized typed configuration loader',
        '3. `src/security/auth.ts` — Authentication verification and cryptographic helpers',
        '4. `src/core/ledger.ts` — ACID double-entry transaction engine',
        '5. `src/api/webhooks.ts` — Partner payment event ingestor (Stripe, Adyen)',
        '',
        '## Ingress Routes',
        '',
        '- `GET /health` — Service readiness and health probe',
        '- `POST /api/v1/ledger/transactions` — Record authenticated double-entry ledger movement (Requires Auth)',
        '- `POST /webhooks/stripe` — Ingest external payment intent settlement notifications',
        '',
        '## Intended Security Behavior',
        '',
        'All mutating ledger operations must be protected by cryptographic identity verification.',
        'Webhook ingress endpoints must strictly verify partner payload signatures against the configured shared secret before triggering downstream ledger mutations. Unverified payloads must be rejected immediately with HTTP 401 Unauthorized.',
        '',
        '## Environment Variables',
        '',
        '- `PORT` — HTTP service listening port (default: 3000)',
        '- `DATABASE_URL` — Connection URI for PostgreSQL ledger database',
        '- `JWT_PUBLIC_KEY` — Cryptographic public key certificate',
        '- `STRIPE_WEBHOOK_SECRET` — Secret used for HMAC-SHA256 webhook signature verification',
        '- `NODE_ENV` — Environment name (development/production)',
      ].join('\n'),
    },
    {
      path: 'src/config.ts',
      content: [
        '/**',
        ' * Centralized Enterprise Configuration Loader',
        ' * Reads process.env and enforces application defaults.',
        ' */',
        '',
        'export interface AppConfig {',
        '  port: number;',
        '  databaseUrl: string;',
        '  jwtPublicKey: string;',
        '  stripeWebhookSecret: string;',
        '  nodeEnv: string;',
        '}',
        '',
        'export const config: AppConfig = {',
        '  // Source default binds to 8080 (Drift: README and .env.example specify 3000)',
        '  port: Number(process.env.PORT) || 8080,',
        '  databaseUrl: process.env.DATABASE_URL || \'postgresql://localhost:5432/payment_core\',',
        '  jwtPublicKey: process.env.JWT_PUBLIC_KEY || \'dev-rsa-public-key\',',
        '  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET || \'whsec_default_secret\',',
        '  nodeEnv: process.env.NODE_ENV || \'development\',',
        '};',
      ].join('\n'),
    },
    {
      path: 'src/security/auth.ts',
      content: [
        'import crypto from \'crypto\';',
        'import jwt from \'jsonwebtoken\';',
        'import { config } from \'../config\';',
        '',
        '/**',
        ' * Enterprise Authentication & Security Service',
        ' *',
        ' * Implements RS256/RSA asymmetric public-key signature verification for API callers.',
        ' * (Note: Specification drift against README which claims HMAC authentication).',
        ' */',
        '',
        'export interface AuthenticatedUser {',
        '  id: string;',
        '  tenantId: string;',
        '  roles: string[];',
        '}',
        '',
        '/**',
        ' * Verify RSA asymmetric public-key token',
        ' */',
        'export function verifyRsaToken(token: string): AuthenticatedUser {',
        '  // RS256 / RSA-style asymmetric signature verification',
        '  const decoded = jwt.verify(token, config.jwtPublicKey, {',
        '    algorithms: [\'RS256\']',
        '  }) as AuthenticatedUser;',
        '',
        '  return decoded;',
        '}',
        '',
        '/**',
        ' * Express middleware to enforce authentication',
        ' */',
        'export function requireAuth(req: any, res: any, next: any) {',
        '  const authHeader = req.headers[\'authorization\'];',
        '  if (!authHeader || !authHeader.startsWith(\'Bearer \')) {',
        '    return res.status(401).json({ error: \'Missing or malformed Authorization bearer header\' });',
        '  }',
        '',
        '  const token = authHeader.split(\' \')[1];',
        '  try {',
        '    req.user = verifyRsaToken(token);',
        '    next();',
        '  } catch (err: any) {',
        '    return res.status(403).json({ error: \'RS256 signature verification failed\', detail: err.message });',
        '  }',
        '}',
        '',
        '/**',
        ' * Cryptographic HMAC-SHA256 signature verification helper for incoming webhooks.',
        ' * This helper exists in the codebase but is NOT imported or called by src/api/webhooks.ts.',
        ' */',
        'export function verifyWebhookSignature(payload: string, signature: string, secret: string): boolean {',
        '  if (!signature || !secret) return false;',
        '',
        '  try {',
        '    const hmac = crypto.createHmac(\'sha256\', secret);',
        '    const expected = \'sha256=\' + hmac.update(payload).digest(\'hex\');',
        '    return crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected));',
        '  } catch {',
        '    return false;',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      path: 'src/core/ledger.ts',
      content: [
        'import { config } from \'../config\';',
        '',
        '/**',
        ' * Enterprise Double-Entry Ledger Engine',
        ' * Handles immutable audit logs and balances.',
        ' */',
        '',
        'export interface LedgerEntry {',
        '  transactionId: string;',
        '  sourceAccount: string;',
        '  destinationAccount: string;',
        '  amountCents: number;',
        '  currency: string;',
        '  reference: string;',
        '  metadata?: Record<string, any>;',
        '}',
        '',
        'export interface LedgerBalance {',
        '  accountId: string;',
        '  clearedBalanceCents: number;',
        '  currency: string;',
        '}',
        '',
        '// In-memory ledger storage simulation',
        'const ledgerStore = new Map<string, LedgerEntry>();',
        'const balances = new Map<string, number>();',
        '',
        '/**',
        ' * Records a double-entry financial transaction.',
        ' * Enforces non-negative balances and records immutable audit record.',
        ' */',
        'export async function recordTransaction(entry: LedgerEntry): Promise<LedgerEntry> {',
        '  // Validate double-entry invariant: amount must be positive',
        '  if (entry.amountCents <= 0) {',
        '    throw new Error(\'Ledger transaction amount must be strictly greater than zero\');',
        '  }',
        '',
        '  // Simulate network/database async I/O',
        '  await new Promise(resolve => setTimeout(resolve, 5));',
        '',
        '  // Update source debit',
        '  const currentSource = balances.get(entry.sourceAccount) || 0;',
        '  balances.set(entry.sourceAccount, currentSource - entry.amountCents);',
        '',
        '  // Update destination credit',
        '  const currentDest = balances.get(entry.destinationAccount) || 0;',
        '  balances.set(entry.destinationAccount, currentDest + entry.amountCents);',
        '',
        '  // Store immutable ledger log',
        '  ledgerStore.set(entry.transactionId, {',
        '    ...entry,',
        '    metadata: {',
        '      ...entry.metadata,',
        '      recordedAt: new Date().toISOString(),',
        '      nodeEnv: config.nodeEnv,',
        '    }',
        '  });',
        '',
        '  return ledgerStore.get(entry.transactionId)!;',
        '}',
        '',
        '/**',
        ' * Retrieves the current balance for a ledger account',
        ' */',
        'export async function getAccountBalance(accountId: string): Promise<LedgerBalance> {',
        '  await new Promise(resolve => setTimeout(resolve, 2));',
        '  return {',
        '    accountId,',
        '    clearedBalanceCents: balances.get(accountId) || 0;',
        '    currency: \'USD\',',
        '  };',
        '}',
      ].join('\n'),
    },
    {
      path: 'src/api/webhooks.ts',
      content: [
        'import express from \'express\';',
        'import { recordTransaction } from \'../core/ledger\';',
        '',
        '/**',
        ' * External Webhook Ingestion Router',
        ' * Receives asynchronous settlement events from payment processors.',
        ' *',
        ' * VULNERABILITY (DEMO FINDING #2):',
        ' * This route handler receives untrusted external webhook payloads and directly',
        ' * triggers ledger movements without validating HMAC-SHA256 signatures.',
        ' * The cryptographic verification helper exists in `src/security/auth.ts`',
        ' * but is not imported or called here.',
        ' */',
        '',
        'export const webhookRouter = express.Router();',
        '',
        'webhookRouter.post(\'/webhooks/stripe\', async (req, res) => {',
        '  const event = req.body;',
        '  const signature = req.headers[\'x-stripe-signature\'] || req.headers[\'x-hub-signature-256\'];',
        '',
        '  try {',
        '    // VULNERABILITY: No signature verification is performed here!',
        '    // An attacker can forge arbitrary payment events and credit ledger balances.',
        '    if (event.type === \'payment_intent.succeeded\') {',
        '      await recordTransaction({',
        '        transactionId: `txn_stripe_${event.data?.object?.id || Date.now()}`,',
        '        sourceAccount: \'acc_external_clearing\',',
        '        destinationAccount: event.data?.object?.metadata?.accountId || \'acc_merchant_settlement\',',
        '        amountCents: event.data?.object?.amount || 10000,',
        '        currency: event.data?.object?.currency || \'USD\',',
        '        reference: `stripe_charge_${Date.now()}`,',
        '      });',
        '    }',
        '',
        '    res.json({ received: true, eventId: event.id });',
        '  } catch (err: any) {',
        '    res.status(500).json({ error: \'Failed to process webhook event\', detail: err.message });',
        '  }',
        '});',
      ].join('\n'),
    },
    {
      path: 'src/server.ts',
      content: [
        'import express from \'express\';',
        'import { config } from \'./config\';',
        'import { webhookRouter } from \'./api/webhooks\';',
        'import { requireAuth } from \'./security/auth\';',
        'import { recordTransaction, getAccountBalance } from \'./core/ledger\';',
        '',
        '/**',
        ' * Enterprise Payment Core Server',
        ' * Main application bootstrap and HTTP route registration.',
        ' */',
        '',
        'export const app = express();',
        'app.use(express.json());',
        '',
        '// Ingress: Public webhook router',
        'app.use(webhookRouter);',
        '',
        '// System health check',
        'app.get(\'/health\', (_req, res) => {',
        '  res.json({',
        '    status: \'HEALTHY\',',
        '    service: \'enterprise-payment-core\',',
        '    environment: config.nodeEnv,',
        '    timestamp: new Date().toISOString(),',
        '  });',
        '});',
        '',
        '// Guarded API: Query account balance',
        'app.get(\'/api/v1/ledger/balance/:id\', requireAuth, async (req, res) => {',
        '  try {',
        '    const balance = await getAccountBalance(req.params.id);',
        '    res.json(balance);',
        '  } catch (err: any) {',
        '    res.status(500).json({ error: err.message });',
        '  }',
        '});',
        '',
        '// Guarded API: Direct ledger transaction injection',
        'app.post(\'/api/v1/ledger/transactions\', requireAuth, async (req, res) => {',
        '  try {',
        '    const entry = await recordTransaction(req.body);',
        '    res.status(201).json(entry);',
        '  } catch (err: any) {',
        '    res.status(400).json({ error: err.message });',
        '  }',
        '});',
        '',
        '// Start HTTP server on configured port (defaults to 8080)',
        'const PORT = config.port;',
        '',
        'if (process.env.NODE_ENV !== \'test\') {',
        '  app.listen(PORT, () => {',
        '    console.log(`[Enterprise Payment Core] Listening on port ${PORT} in ${config.nodeEnv} mode`);',
        '  });',
        '}',
      ].join('\n'),
    },
    {
      path: 'tests/existing.test.ts',
      content: [
        'import { describe, it, expect } from \'vitest\';',
        'import { config } from \'../src/config\';',
        'import { recordTransaction, getAccountBalance } from \'../src/core/ledger\';',
        'import { verifyWebhookSignature } from \'../src/security/auth\';',
        '',
        'describe(\'Enterprise Payment Core Baseline Test Suite\', () => {',
        '  it(\'config resolves valid default port\', () => {',
        '    expect(config.port).toBe(8080);',
        '    expect(config.nodeEnv).toBeDefined();',
        '  });',
        '',
        '  it(\'ledger double-entry records transactions with positive balances\', async () => {',
        '    const entry = await recordTransaction({',
        '      transactionId: \'txn_test_baseline_01\',',
        '      sourceAccount: \'acc_source_100\',',
        '      destinationAccount: \'acc_dest_200\',',
        '      amountCents: 5000,',
        '      currency: \'USD\',',
        '      reference: \'ref_baseline_test\',',
        '    });',
        '',
        '    expect(entry.transactionId).toBe(\'txn_test_baseline_01\');',
        '    expect(entry.amountCents).toBe(5000);',
        '',
        '    const balance = await getAccountBalance(\'acc_dest_200\');',
        '    expect(balance.clearedBalanceCents).toBe(5000);',
        '  });',
        '',
        '  it(\'ledger rejects zero or negative transaction amounts\', async () => {',
        '    await expect(recordTransaction({',
        '      transactionId: \'txn_invalid\',',
        '      sourceAccount: \'acc_1\',',
        '      destinationAccount: \'acc_2\',',
        '      amountCents: -100,',
        '      currency: \'USD\',',
        '      reference: \'ref_neg\',',
        '    })).rejects.toThrow(\'greater than zero\');',
        '  });',
        '',
        '  it(\'auth helper verifyWebhookSignature properly validates HMAC signatures\', () => {',
        '    const payload = JSON.stringify({ event: \'test\' });',
        '    const secret = \'test_secret_123\';',
        '    expect(verifyWebhookSignature(payload, \'\', secret)).toBe(false);',
        '  });',
        '});',
      ].join('\n'),
    },
  ];

  return {
    files: files.map(f => ({
      path: f.path,
      content: f.content,
      language: detectLanguage(f.path),
    })),
    metadata: {
      source: 'demo',
      name: 'enterprise-payment-core',
      loadedAt: new Date().toISOString(),
      description: 'Canonical enterprise payment core fixture with intentional controlled specification drift and unverified webhook ingress.',
    },
  };
}

/** @param {string} filePath */
function detectLanguage(filePath) {
  const ext = filePath.split('.').pop()?.toLowerCase();
  const map = {
    js: 'javascript', mjs: 'javascript', cjs: 'javascript',
    ts: 'typescript', tsx: 'typescript', jsx: 'javascript',
    json: 'json', yaml: 'yaml', yml: 'yaml',
    md: 'markdown', py: 'python', rb: 'ruby',
    go: 'go', rs: 'rust', java: 'java', cs: 'csharp',
    html: 'html', css: 'css', sql: 'sql',
    proto: 'protobuf', toml: 'toml', xml: 'xml',
  };
  return map[ext] || 'plaintext';
}
