/**
 * PR Formatter
 *
 * Formats an atomic, enterprise-ready Pull Request payload from the combined
 * outputs of all three MSE subagents.
 *
 * The PR payload contains:
 *   1. Executive summary  -- violated invariant + severity + energy delta
 *   2. Antigen test file  -- synthesized counterexample (the "proof of failure")
 *   3. Multi-file diff    -- patch descriptors from the Patch Synthesizer
 *   4. Verification proof -- RED→GREEN state transition evidence
 *   5. Benchmark telemetry -- ops/sec for synthesis + drift score
 *
 * Output formats:
 *   formatMarkdown(payload)  → GitHub PR description (Markdown)
 *   formatJSON(payload)      → machine-readable structured object
 *   writePR(payload, dir)    → writes both formats to outputDir/pr/
 */

import fs   from 'node:fs';
import path from 'node:path';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * @typedef {{
 *   title: string,
 *   branchName: string,
 *   invariantId: string,
 *   invariantName: string,
 *   invariantType: string,
 *   severity: string,
 *   affectedFiles: string[],
 *   energyBefore: number,
 *   energyAfter: number,
 *   dIntentScore: number,
 *   antigenFile: string,
 *   antigenSource: string,
 *   patches: import('../cegis/patchSynthesizer.js').PatchResult[],
 *   verificationState: string,
 *   verificationOutput: string,
 *   durationMs: number,
 *   benchmarkOps: number,
 *   generatedAt: string,
 * }} PRPayload
 */

// ---------------------------------------------------------------------------
// Branch name sanitiser
// ---------------------------------------------------------------------------

/**
 * Convert an invariant ID + name into a valid git branch name.
 * @param {string} id
 * @param {string} name
 * @returns {string}
 */
export function formatBranchName(id, name) {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return `mse/auto-patch/${id.toLowerCase()}-${slug}`;
}

// ---------------------------------------------------------------------------
// Markdown formatter
// ---------------------------------------------------------------------------

/**
 * Render the PR payload as a GitHub-compatible Markdown PR description.
 * @param {PRPayload} payload
 * @returns {string}
 */
export function formatMarkdown(payload) {
  const energyDelta = (payload.energyBefore - payload.energyAfter).toFixed(4);
  const stateIcon   = payload.verificationState === 'GREEN' ? 'VERIFIED' :
                      payload.verificationState === 'RED'   ? 'UNVERIFIED' : 'PENDING';

  const patchBlocks = payload.patches.map(p => `
### ${p.targetFile}

**Strategy:** \`${p.strategy}\`
**Confidence:** ${p.confidence}

${p.description}

\`\`\`diff
${p.diff}
\`\`\`

**Repaired snippet:**
\`\`\`js
${p.repairedSnippet}
\`\`\`

**Postconditions verified:**
${p.postconditions.map(c => `- ${c}`).join('\n')}
`).join('\n---\n');

  return `## MSE Auto-Patch: ${payload.invariantName}

**Branch:** \`${payload.branchName}\`
**Invariant ID:** \`${payload.invariantId}\`
**Type:** ${payload.invariantType} | **Severity:** ${payload.severity}
**Verification:** ${stateIcon}
**Generated:** ${payload.generatedAt}

---

### Invariant Violation Summary

The MSE Morphologist detected a **${payload.severity}** invariant violation
in the following file(s): ${payload.affectedFiles.map(f => `\`${f}\``).join(', ')}.

| Metric | Before patch | After patch |
|---|---|---|
| System energy E(S) | \`${payload.energyBefore.toFixed(4)}\` | \`${payload.energyAfter.toFixed(4)}\` |
| Energy delta | | \`-${energyDelta}\` |
| D_intent score | \`${payload.dIntentScore.toFixed(4)}\` | |
| Synthesis speed | | \`${payload.benchmarkOps.toLocaleString()} ops/sec\` |

---

### Synthesized Counterexample (Antigen Test)

File: \`${payload.antigenFile}\`

\`\`\`js
${payload.antigenSource.trim()}
\`\`\`

---

### Patch Descriptors

${patchBlocks}

---

### Verification Proof

State transition: **UNKNOWN** -> **${payload.verificationState}**

${payload.verificationOutput
    ? '```\n' + payload.verificationOutput.slice(0, 1200).trim() + '\n```'
    : '_Verification was skipped (set `runVerification: true` to enable)._'}

---

*Generated by MSE Immune Core v1.0.0 in ${payload.durationMs}ms.*
`;
}

// ---------------------------------------------------------------------------
// JSON formatter
// ---------------------------------------------------------------------------

/**
 * Render the PR payload as a machine-readable JSON object.
 * @param {PRPayload} payload
 * @returns {object}
 */
export function formatJSON(payload) {
  return {
    schemaVersion: '1.0.0',
    generatedAt:   payload.generatedAt,
    pr: {
      title:      payload.title,
      branchName: payload.branchName,
      body:       formatMarkdown(payload),
    },
    invariant: {
      id:            payload.invariantId,
      name:          payload.invariantName,
      type:          payload.invariantType,
      severity:      payload.severity,
      affectedFiles: payload.affectedFiles,
    },
    telemetry: {
      energyBefore:      payload.energyBefore,
      energyAfter:       payload.energyAfter,
      dIntentScore:      payload.dIntentScore,
      durationMs:        payload.durationMs,
      benchmarkOps:      payload.benchmarkOps,
      verificationState: payload.verificationState,
    },
    antigen: {
      file:   payload.antigenFile,
      source: payload.antigenSource,
    },
    patches: payload.patches,
  };
}

// ---------------------------------------------------------------------------
// File writer
// ---------------------------------------------------------------------------

/**
 * Write the full PR payload to disk in both Markdown and JSON formats.
 *
 * Output:
 *   {outputDir}/pr/{invariantId}.md
 *   {outputDir}/pr/{invariantId}.json
 *   {outputDir}/pr/antigens/{antigenFile}
 *
 * @param {PRPayload} payload
 * @param {string} outputDir
 * @returns {{ mdPath: string, jsonPath: string, antigenPath: string }}
 */
export function writePR(payload, outputDir) {
  const prDir = path.join(outputDir, 'pr');
  fs.mkdirSync(prDir, { recursive: true });

  const safeId   = payload.invariantId.replace(/[^A-Za-z0-9-]/g, '_');
  const mdPath   = path.join(prDir, `${safeId}.md`);
  const jsonPath = path.join(prDir, `${safeId}.json`);

  const antigenDir  = path.join(prDir, 'antigens');
  fs.mkdirSync(antigenDir, { recursive: true });
  const antigenPath = path.join(antigenDir, path.basename(payload.antigenFile));
  fs.writeFileSync(antigenPath, payload.antigenSource, 'utf8');

  fs.writeFileSync(mdPath,   formatMarkdown(payload), 'utf8');
  fs.writeFileSync(jsonPath, JSON.stringify(formatJSON(payload), null, 2), 'utf8');

  return { mdPath, jsonPath, antigenPath };
}
